# Generated by Django 2.2.7 on 2022-03-28 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('subject', models.TextField(max_length=120, verbose_name='Subject')),
                ('message', models.TextField(max_length=120, verbose_name='Message')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('ingredients', models.EmailField(max_length=50, verbose_name='ingredients')),
                ('price', models.TextField(max_length=120, verbose_name='price')),
            ],
        ),
    ]
