# Generated by Django 4.0.3 on 2022-03-28 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_product_price_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ingredients',
            field=models.TextField(max_length=50, verbose_name='ingredients'),
        ),
    ]
