# Generated by Django 4.0.3 on 2022-03-29 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_product_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.CharField(default=2, max_length=120, verbose_name='name'),
            preserve_default=False,
        ),
    ]
