# Generated by Django 4.0.3 on 2022-04-03 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name='Name')),
                ('PhoneNumber', models.CharField(max_length=100, verbose_name='Phone Number')),
                ('Email', models.CharField(max_length=100, verbose_name='Email')),
                ('Message', models.CharField(max_length=100, verbose_name='Message')),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='test',
        ),
    ]
