# Generated by Django 4.0.3 on 2022-04-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_contactdetails_delete_contact_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('review', models.TextField(max_length=500, verbose_name='review')),
            ],
        ),
    ]
