# Generated by Django 4.0.3 on 2022-04-06 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('journey', models.CharField(max_length=120, verbose_name='journey')),
                ('content', models.TextField(max_length=300, verbose_name='content')),
                ('desciption', models.TextField(max_length=300, verbose_name='description')),
                ('pointa', models.TextField(max_length=300, verbose_name='pointa')),
                ('pointb', models.TextField(max_length=300, verbose_name='pointb')),
                ('pointc', models.TextField(max_length=300, verbose_name='pointc')),
            ],
        ),
        migrations.AlterField(
            model_name='contactdetails',
            name='Email',
            field=models.EmailField(max_length=100, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contactdetails',
            name='Message',
            field=models.TextField(max_length=100, verbose_name='Message'),
        ),
    ]
