# Generated by Django 4.0.3 on 2022-04-06 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_about_alter_contactdetails_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='conclusion',
            field=models.TextField(default=0, max_length=300, verbose_name='conclusion'),
        ),
    ]
