# Generated by Django 4.0.3 on 2022-04-07 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_about_conclusion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Why',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialno', models.CharField(max_length=120, verbose_name='serialno')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('description', models.TextField(max_length=2000, verbose_name='description')),
            ],
        ),
        migrations.DeleteModel(
            name='About',
        ),
    ]
